# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='aa'),
            preserve_default=False,
        ),
    ]
